apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: learndemo.azurecr.io/worker:64db7419d4c7ec43300dc52dece0f1eab43316b7
        name: worker
      imagePullSecrets:
      - name: acr-secret
