apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: learnazacr.azurecr.io/worker:91b8832cdc7c735053099e295bfcfd2119864c3e
        name: worker
      imagePullSecrets:
      - name: acr-secret
