name: Vote Build and Push to ACR

on:
  push:
    branches: [ main ]
    paths:
      - 'vote/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build the vote image and push it to ACR
        uses: docker/build-push-action@v5
        with:
          context: vote
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/vote:${{ github.sha }}
          file: vote/Dockerfile

      - name: Update vote-deployment.yaml with new image tag
        run: |
          sed -i '/image:/s|image: .*|image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/vote:${{ github.sha }}|' k8s-specifications/vote-deployment.yaml
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s-specifications/vote-deployment.yaml
          git commit -m "Update image tag in vote-deployment.yaml"
          git push
