name: Worker Build and Push to ACR

on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build the worker image and push it to ACR
        uses: docker/build-push-action@v5
        with:
          context: worker
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/worker:${{ github.sha }}
          file: worker/Dockerfile
      
      - name: Update worker-deployment.yaml with new image tag
        run: |
          sed -i '/image:/s|image: .*|image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/worker:${{ github.sha }}|' k8s-specifications/worker-deployment.yaml
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s-specifications/worker-deployment.yaml
          git commit -m "Update image tag in worker-deployment.yaml"
          git push
